-- HIGHWAYLOT -- Shipping-referral lead capture table
--
-- Run this in the Supabase SQL editor whenever you're ready to actually turn
-- this feature on (after real legal review — see the comment above
-- SHIPPING_REFERRAL_ENABLED in src/App.jsx). The frontend code is already
-- built and shipped, but stays fully inert (renders nothing, no inserts
-- happen) until that flag is flipped to true AND this table exists.
--
-- jev-tested spec: shipping only (financing/insurance excluded), opt-in,
-- buyer-initiated, no money ever touched by HIGHWAYLOT. This table only
-- captures the opt-in lead -- there is no partner integration here. Actually
-- sending leads to a real shipping partner (uShip/Montway/etc.) is separate
-- follow-up work once you have one under contract.

create table if not exists public.shipping_leads (
  id               bigint generated by default as identity primary key,
  listing_id       bigint not null references public.listings(id),
  name             text,
  email            text not null,
  destination_zip  text not null,
  source           text,
  session_id       text,
  created_at       timestamptz not null default now()
);

alter table public.shipping_leads enable row level security;

-- Anon can insert their own opt-in lead (same pattern as your other write
-- tables) but can never read leads back -- no select policy at all.
drop policy if exists "anon can submit shipping leads" on public.shipping_leads;
create policy "anon can submit shipping leads"
  on public.shipping_leads
  for insert
  to anon
  with check (true);

-- Same rate-limit pattern as sql/round2_abuse_protection.sql -- reuses
-- check_rate_limit() from that file, so run that one first if you haven't.
create or replace function public.enforce_shipping_leads_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.check_rate_limit('shipping_leads_insert', 10, 3600) then
    raise exception 'Too many shipping quote requests recently from this connection -- please try again in a bit.'
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_shipping_leads_rate_limit on public.shipping_leads;
create trigger trg_shipping_leads_rate_limit
  before insert on public.shipping_leads
  for each row execute function public.enforce_shipping_leads_rate_limit();
